name = "WTF Overloaded"
author = "TM4"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd86bc3e8f71aca575b139e26d75b059ac4a60e74812ff8503493b4fe62c5d84"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
